# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique asset code', max_length=50, unique=True, verbose_name='Asset Code')),
                ('name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('process', models.CharField(blank=True, help_text='Process this asset belongs to', max_length=100, null=True, verbose_name='Process')),
                ('equipment_id', models.CharField(blank=True, help_text='Equipment ID from external system', max_length=50, null=True, verbose_name='Equipment ID')),
                ('machine_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Machine Name')),
                ('location_path', models.CharField(blank=True, help_text='Full location path: Factory/Workshop/Line/Station', max_length=255, null=True, verbose_name='Location Path')),
                ('factory', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factory')),
                ('workshop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Workshop')),
                ('line', models.CharField(blank=True, max_length=50, null=True, verbose_name='Production Line')),
                ('station', models.CharField(blank=True, max_length=50, null=True, verbose_name='Station')),
                ('vendor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vendor/Manufacturer')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('start_date', models.DateField(blank=True, help_text='Date when asset was commissioned', null=True, verbose_name='Start Date')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Warranty Expiry')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('retired', 'Retired'), ('maintenance', 'Under Maintenance')], default='active', max_length=20, verbose_name='Status')),
                ('criticality', models.CharField(choices=[('critical', 'Critical'), ('important', 'Important'), ('normal', 'Normal')], default='normal', max_length=20, verbose_name='Criticality')),
                ('cost_center', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cost Center')),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Asset Value')),
                ('expected_life_years', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Expected Life (Years)')),
                ('current_meter_reading', models.DecimalField(decimal_places=2, default=0, help_text='Current counter value (e.g., running hours, production count)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Meter Reading')),
                ('meter_unit', models.CharField(blank=True, help_text='Unit for meter reading (e.g., hours, cycles, pieces)', max_length=20, null=True, verbose_name='Meter Unit')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Last Maintenance Date')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Next Maintenance Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'assets',
                'ordering': ['code'],
            },
        ),
    ]
