# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assets', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent asset for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='assets.asset', verbose_name='Parent Asset'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['code'], name='assets_code_5f20be_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status'], name='assets_status_326766_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['factory', 'workshop', 'line'], name='assets_factory_130ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['parent'], name='assets_parent__3f1a47_idx'),
        ),
    ]
