# Generated by Django 5.2.9 on 2026-01-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('report_type', models.CharField(max_length=50, verbose_name='Report Type')),
                ('parameters', models.JSONField(blank=True, default=dict, verbose_name='Parameters')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('output_file', models.CharField(blank=True, max_length=255, null=True, verbose_name='Output File')),
                ('output_format', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('xlsx', 'Excel'), ('csv', 'CSV')], max_length=10, null=True, verbose_name='Output Format')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Error Message')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Report Run',
                'verbose_name_plural': 'Report Runs',
                'db_table': 'report_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Report Name')),
                ('report_type', models.CharField(choices=[('workorder_summary', 'Work Order Summary'), ('downtime_analysis', 'Downtime Analysis'), ('spareparts_usage', 'Spare Parts Usage'), ('maintenance_compliance', 'Maintenance Compliance'), ('cost_analysis', 'Cost Analysis'), ('technician_performance', 'Technician Performance'), ('equipment_availability', 'Equipment Availability')], max_length=50, verbose_name='Report Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20, verbose_name='Frequency')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Report-specific parameters and filters', verbose_name='Parameters')),
                ('recipients', models.JSONField(blank=True, default=list, help_text='List of email addresses to send report to', verbose_name='Recipients')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='active', max_length=20, verbose_name='Status')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Run At')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Next Run At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'db_table': 'scheduled_reports',
                'ordering': ['name'],
            },
        ),
    ]
