# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_reports', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='reportrun',
            name='scheduled_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='reports.scheduledreport', verbose_name='Scheduled Report'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['report_type', 'created_at'], name='report_runs_report__a2eddc_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrun',
            index=models.Index(fields=['status', 'created_at'], name='report_runs_status_56b995_idx'),
        ),
    ]
