# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('adjust', 'Adjustment')], max_length=20, verbose_name='Transaction Type')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive value. Direction determined by transaction type.', max_digits=10, verbose_name='Quantity')),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock Before')),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Stock After')),
                ('reference', models.CharField(blank=True, help_text='PO number, invoice number, or other reference', max_length=100, null=True, verbose_name='Reference')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='Remark')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Part Transaction',
                'verbose_name_plural': 'Part Transactions',
                'db_table': 'part_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pr_code', models.CharField(max_length=50, unique=True, verbose_name='PR Code')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Urgency')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('received', 'Received'), ('canceled', 'Canceled')], default='draft', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Reason')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('expected_delivery_date', models.DateField(blank=True, null=True, verbose_name='Expected Delivery Date')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='Actual Delivery Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Purchase Request',
                'verbose_name_plural': 'Purchase Requests',
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_code', models.CharField(db_index=True, help_text='Unique part code/SKU', max_length=50, unique=True, verbose_name='Part Code')),
                ('name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('spec', models.CharField(blank=True, max_length=200, null=True, verbose_name='Specification')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
                ('unit', models.CharField(help_text='Unit of measurement (e.g., pcs, kg, m)', max_length=20, verbose_name='Unit')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier')),
                ('supplier_part_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Supplier Part Code')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Stock')),
                ('safety_stock', models.DecimalField(decimal_places=2, default=0, help_text='Minimum stock level to prevent stockout', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Safety Stock')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, help_text='Reorder point - trigger reorder when below this level', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Min Stock')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum stock level to avoid overstocking', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max Stock')),
                ('reorder_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reorder Quantity')),
                ('location', models.CharField(blank=True, help_text='Warehouse/bin location', max_length=100, null=True, verbose_name='Storage Location')),
                ('shelf', models.CharField(blank=True, max_length=50, null=True, verbose_name='Shelf/Bin')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Cost')),
                ('average_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Average Cost')),
                ('compatible_equipment', models.JSONField(blank=True, default=list, help_text='List of equipment codes this part is compatible with', verbose_name='Compatible Equipment')),
                ('alternative_parts', models.JSONField(blank=True, default=list, help_text='List of alternative part codes', verbose_name='Alternative Parts')),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Days from order to delivery', null=True, verbose_name='Lead Time (Days)')),
                ('lifecycle_status', models.CharField(choices=[('active', 'Active'), ('obsolete', 'Obsolete'), ('discontinued', 'Discontinued')], default='active', max_length=20, verbose_name='Lifecycle Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
                'db_table': 'spare_parts',
                'ordering': ['part_code'],
            },
        ),
    ]
