# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spareparts', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parttransaction',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Operator'),
        ),
        migrations.AddField(
            model_name='parttransaction',
            name='related_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_transactions', to='workorders.workorder', verbose_name='Related Work Order'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By'),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_spare_parts', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requests', to='spareparts.sparepart', verbose_name='Part'),
        ),
        migrations.AddField(
            model_name='parttransaction',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='spareparts.sparepart', verbose_name='Part'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['part_code'], name='spare_parts_part_co_999adc_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['category'], name='spare_parts_categor_e0472e_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['lifecycle_status'], name='spare_parts_lifecyc_d35632_idx'),
        ),
        migrations.AddIndex(
            model_name='parttransaction',
            index=models.Index(fields=['part', 'created_at'], name='part_transa_part_id_3a61fd_idx'),
        ),
        migrations.AddIndex(
            model_name='parttransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='part_transa_transac_3c026f_idx'),
        ),
        migrations.AddIndex(
            model_name='parttransaction',
            index=models.Index(fields=['related_work_order'], name='part_transa_related_e39208_idx'),
        ),
    ]
