# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique maintenance plan code', max_length=50, unique=True, verbose_name='Plan Code')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('trigger_type', models.CharField(choices=[('time', 'Time Based'), ('counter', 'Counter Based')], default='time', max_length=20, verbose_name='Trigger Type')),
                ('frequency_value', models.PositiveIntegerField(blank=True, help_text='Number of time units between maintenance', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Frequency Value')),
                ('frequency_unit', models.CharField(blank=True, choices=[('day', 'Day(s)'), ('week', 'Week(s)'), ('month', 'Month(s)'), ('quarter', 'Quarter(s)'), ('year', 'Year(s)')], max_length=20, null=True, verbose_name='Frequency Unit')),
                ('counter_name', models.CharField(blank=True, help_text='Name of the counter (e.g., Running Hours, Production Count)', max_length=50, null=True, verbose_name='Counter Name')),
                ('counter_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Counter value threshold to trigger maintenance', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Counter Threshold')),
                ('checklist_template', models.JSONField(default=list, help_text='JSON array of checklist items for this maintenance plan', verbose_name='Checklist Template')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Hours')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Estimated Cost')),
                ('required_skills', models.CharField(blank=True, max_length=200, null=True, verbose_name='Required Skills')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20, verbose_name='Priority')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is currently active', verbose_name='Active')),
                ('last_generated_date', models.DateField(blank=True, help_text='Last date a work order was generated from this plan', null=True, verbose_name='Last Generated Date')),
                ('last_counter_value', models.DecimalField(blank=True, decimal_places=2, help_text='Last counter value when work order was generated', max_digits=12, null=True, verbose_name='Last Counter Value')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Maintenance Plan',
                'verbose_name_plural': 'Maintenance Plans',
                'db_table': 'maintenance_plans',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Template Code')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('work_order_type', models.CharField(choices=[('PM', 'Preventive Maintenance'), ('CM', 'Corrective Maintenance'), ('inspection', 'Inspection')], default='PM', max_length=20, verbose_name='Work Order Type')),
                ('checklist_template', models.JSONField(default=list, verbose_name='Checklist Template')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Estimated Hours')),
                ('required_skills', models.CharField(blank=True, max_length=200, null=True, verbose_name='Required Skills')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Work Order Template',
                'verbose_name_plural': 'Work Order Templates',
                'db_table': 'work_order_templates',
                'ordering': ['code'],
            },
        ),
    ]
