# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceplan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenance_plans', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='maintenanceplan',
            name='equipment',
            field=models.ForeignKey(help_text='Asset this plan applies to', on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='assets.asset', verbose_name='Equipment'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['code'], name='maintenance_code_890810_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['equipment', 'is_active'], name='maintenance_equipme_41adf9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceplan',
            index=models.Index(fields=['trigger_type'], name='maintenance_trigger_ecb0dd_idx'),
        ),
    ]
