# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionRoute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Route Code')),
                ('name', models.CharField(max_length=200, verbose_name='Route Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('route_items', models.JSONField(help_text='JSON array defining equipment sequence and templates', verbose_name='Route Items')),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Duration (Minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Inspection Route',
                'verbose_name_plural': 'Inspection Routes',
                'db_table': 'inspection_routes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Template Code')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('items_template', models.JSONField(help_text='JSON array defining inspection items structure', verbose_name='Items Template')),
                ('equipment_type', models.CharField(blank=True, help_text='Type of equipment this template applies to', max_length=50, null=True, verbose_name='Equipment Type')),
                ('frequency_days', models.PositiveIntegerField(blank=True, help_text='How often this inspection should be performed', null=True, verbose_name='Frequency (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Inspection Template',
                'verbose_name_plural': 'Inspection Templates',
                'db_table': 'inspection_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InspectionRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(blank=True, help_text='Inspection route name if part of a route', max_length=100, null=True, verbose_name='Route')),
                ('items', models.JSONField(help_text='JSON array of inspection items with values and results', verbose_name='Inspection Items')),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('warning', 'Warning')], default='pass', max_length=20, verbose_name='Overall Result')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_records', to='assets.asset', verbose_name='Equipment')),
            ],
            options={
                'verbose_name': 'Inspection Record',
                'verbose_name_plural': 'Inspection Records',
                'db_table': 'inspection_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
