# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspections', '0001_initial'),
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionrecord',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to=settings.AUTH_USER_MODEL, verbose_name='Inspector'),
        ),
        migrations.AddField(
            model_name='inspectionrecord',
            name='triggered_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_inspections', to='workorders.workorder', verbose_name='Triggered Work Order'),
        ),
        migrations.AddField(
            model_name='inspectionroute',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspection_routes', to=settings.AUTH_USER_MODEL, verbose_name='Default Inspector'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['equipment', 'created_at'], name='inspection__equipme_e2917d_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['inspector', 'created_at'], name='inspection__inspect_0a0663_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectionrecord',
            index=models.Index(fields=['result', 'created_at'], name='inspection__result_43a83c_idx'),
        ),
    ]
