# Generated by Django 5.2.9 on 2026-01-08 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wo_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Work Order Code')),
                ('wo_type', models.CharField(choices=[('PM', 'Preventive Maintenance'), ('CM', 'Corrective Maintenance'), ('inspection', 'Inspection')], default='CM', max_length=20, verbose_name='Work Order Type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('canceled', 'Canceled')], db_index=True, default='open', max_length=20, verbose_name='Status')),
                ('summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned At')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='Planned Start')),
                ('planned_end', models.DateTimeField(blank=True, null=True, verbose_name='Planned End')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Actual Start')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Actual End')),
                ('failure_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Failure Code')),
                ('root_cause', models.TextField(blank=True, null=True, verbose_name='Root Cause')),
                ('actions_taken', models.TextField(blank=True, null=True, verbose_name='Actions Taken')),
                ('checklist', models.JSONField(blank=True, default=list, help_text='Checklist items with results', verbose_name='Checklist')),
                ('downtime_minutes', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Downtime (Minutes)')),
                ('labor_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Labor Hours')),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Parts Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Cost')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Attachments')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Completed By')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='assets.asset', verbose_name='Equipment')),
                ('maintenance_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.maintenanceplan', verbose_name='Maintenance Plan')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
            options={
                'verbose_name': 'Work Order',
                'verbose_name_plural': 'Work Orders',
                'db_table': 'work_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('is_internal', models.BooleanField(default=True, verbose_name='Internal Only')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order_comments', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Work Order Comment',
                'verbose_name_plural': 'Work Order Comments',
                'db_table': 'work_order_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('part_code', models.CharField(max_length=50, verbose_name='Part Code')),
                ('part_name', models.CharField(max_length=200, verbose_name='Part Name')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Quantity')),
                ('unit', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Cost')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Cost')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='workorders.workorder', verbose_name='Work Order')),
            ],
            options={
                'verbose_name': 'Work Order Part',
                'verbose_name_plural': 'Work Order Parts',
                'db_table': 'work_order_parts',
                'ordering': ['part_code'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['wo_code'], name='work_orders_wo_code_2ada5a_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['equipment', 'status'], name='work_orders_equipme_35550f_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'created_at'], name='work_orders_status_2af962_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['wo_type', 'status'], name='work_orders_wo_type_c4ad5e_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assignee', 'status'], name='work_orders_assigne_f50155_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['priority', 'status'], name='work_orders_priorit_72b397_idx'),
        ),
    ]
